class MainPageLocators:
    BTN_CONSTRUCTOR = ("css selector", "a[href='/']")
    BTN_ORDER_FEED = ("css selector", "a[href='/feed']")
    BTN_PERSONAL_ACCOUNT = ("css selector", "a[href='/account']")
    BTN_LOGIN = ("xpath", "//button[text()='Войти в аккаунт']")
    BTN_ORDER = ("xpath", "//button[text()='Оформить заказ']")
    TITLE_MAIN = ("css selector", "h1.text_type_main-large")
    TAB_BUNS = ("xpath", "//div[contains(@class, 'tab_tab__1SPyG')]/span[text()='Булки']")
    TAB_SAUCES = ("xpath", "//div[contains(@class, 'tab_tab__1SPyG')]/span[text()='Соусы']")
    TAB_FILLINGS = ("xpath", "//div[contains(@class, 'tab_tab__1SPyG')]/span[text()='Начинки']")
    INGREDIENT = ("css selector", "img.BurgerIngredient_ingredient__image__3e-07")
    INGREDIENT_COUNTER = ("css selector", "div.counter_counter__ZNLkj p.counter_counter__num__3nue1")
    MODAL_INGREDIENT = ("css selector", "div.Modal_modal__container__Wo2l_")
    MODAL_INGREDIENT_NAME = ("css selector", "div.Modal_modal__container__Wo2l_ p.text_type_main-medium")
    MODAL_CLOSE = ("css selector", "button.Modal_modal__close__TnseK")
    ORDER_NUMBER = ("css selector", "h2.Modal_modal__title_shadow__3ikwq")
    BASKET_TOP_BUN = ("css selector", ".constructor-element_pos_top")
    BASKET_BOTTOM_BUN = ("css selector", ".constructor-element_pos_bottom")